require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });

const CUSTOMER_PORTAL_HOST = process.env.CUSTOMER_PORTAL_HOST || 'oasis.apexinfosys.in';
const ADMIN_PORTAL_HOST = process.env.ADMIN_PORTAL_HOST || 'vista.apexinfosys.in';
const CLOUD_BASE_DOMAIN = process.env.CLOUD_BASE_DOMAIN || 'cloud.apexinfosys.in';
const DEVICE_TUNNEL_HOST = process.env.DEVICE_TUNNEL_HOST || CLOUD_BASE_DOMAIN;
const ADMIN_SSH_JUMP_HOST = 'cloud.apexinfosys.in';
const ADMIN_SSH_JUMP_USER = 'fleetadmin';
const ADMIN_SSH_JUMP_PORT = 22;
const ADMIN_SSH_TARGET_HOST = '127.0.0.1';
const GOOGLE_HOME_CLIENT_ID = process.env.GOOGLE_HOME_CLIENT_ID || '';
const GOOGLE_HOME_CLIENT_SECRET = process.env.GOOGLE_HOME_CLIENT_SECRET || '';
const GOOGLE_HOME_REDIRECT_URI_HOSTS = (
    process.env.GOOGLE_HOME_REDIRECT_URI_HOSTS || 'oauth-redirect.googleusercontent.com'
)
    .split(',')
    .map((item) => item.trim().toLowerCase())
    .filter(Boolean);
const GOOGLE_HOME_AUTH_CODE_TTL_SECONDS = Number(process.env.GOOGLE_HOME_AUTH_CODE_TTL_SECONDS || 600);
const GOOGLE_HOME_ACCESS_TOKEN_TTL_SECONDS = Number(process.env.GOOGLE_HOME_ACCESS_TOKEN_TTL_SECONDS || 3600);
const GOOGLE_HOME_COMMAND_TTL_SECONDS = Number(process.env.GOOGLE_HOME_COMMAND_TTL_SECONDS || 45);
const GOOGLE_HOMEGRAPH_SCOPE = 'https://www.googleapis.com/auth/homegraph';
const GOOGLE_HOMEGRAPH_DEFAULT_TOKEN_URI = 'https://oauth2.googleapis.com/token';
const GOOGLE_HOMEGRAPH_API_BASE_URL = 'https://homegraph.googleapis.com/v1';
const GOOGLE_HOMEGRAPH_REQUEST_SYNC_DEBOUNCE_MS = Number(process.env.GOOGLE_HOMEGRAPH_REQUEST_SYNC_DEBOUNCE_MS || 2500);
const GOOGLE_HOMEGRAPH_REPORT_STATE_DEBOUNCE_MS = Number(process.env.GOOGLE_HOMEGRAPH_REPORT_STATE_DEBOUNCE_MS || 1200);
const GOOGLE_HOMEGRAPH_REPORT_STATE_ENABLED = process.env.GOOGLE_HOMEGRAPH_REPORT_STATE_ENABLED === '0' ? false : true;
const GOOGLE_DEBUG_ENDPOINTS_ENABLED = process.env.GOOGLE_DEBUG_ENDPOINTS_ENABLED === '1';
const ALLOWED_CORS_ORIGINS = (process.env.ALLOWED_CORS_ORIGINS || '')
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
const PORTAL_SESSION_COOKIE_NAME = 'apx_portal_session';
const PORTAL_SESSION_COOKIE_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;
const PORTAL_SESSION_COOKIE_SECURE = process.env.PORTAL_COOKIE_SECURE === '0' ? false : true;
const PORTAL_SESSION_COOKIE_DOMAIN = process.env.PORTAL_COOKIE_DOMAIN || '.apexinfosys.in';
const DEVICE_HEARTBEAT_TIMEOUT_SECONDS = Number(process.env.DEVICE_HEARTBEAT_TIMEOUT_SECONDS || 45);
const DEVICE_HEARTBEAT_INTERVAL_SECONDS = Number(process.env.DEVICE_HEARTBEAT_INTERVAL_SECONDS || 20);
const ADMIN_CONNECT_TOKEN_TTL_MINUTES = Number(process.env.ADMIN_CONNECT_TOKEN_TTL_MINUTES || 10);
const DEVICE_TUNNEL_PORT_MIN = Number(process.env.DEVICE_TUNNEL_PORT_MIN || 22000);
const DEVICE_TUNNEL_PORT_MAX = Number(process.env.DEVICE_TUNNEL_PORT_MAX || 22999);
const DEVICE_TOKEN_PREFIX = 'dvc_';
const ADMIN_CONNECT_TOKEN_PREFIX = 'acn_';

module.exports = {
    CUSTOMER_PORTAL_HOST,
    ADMIN_PORTAL_HOST,
    CLOUD_BASE_DOMAIN,
    DEVICE_TUNNEL_HOST,
    ADMIN_SSH_JUMP_HOST,
    ADMIN_SSH_JUMP_USER,
    ADMIN_SSH_JUMP_PORT,
    ADMIN_SSH_TARGET_HOST,
    GOOGLE_HOME_CLIENT_ID,
    GOOGLE_HOME_CLIENT_SECRET,
    GOOGLE_HOME_REDIRECT_URI_HOSTS,
    GOOGLE_HOME_AUTH_CODE_TTL_SECONDS,
    GOOGLE_HOME_ACCESS_TOKEN_TTL_SECONDS,
    GOOGLE_HOME_COMMAND_TTL_SECONDS,
    GOOGLE_HOMEGRAPH_SCOPE,
    GOOGLE_HOMEGRAPH_DEFAULT_TOKEN_URI,
    GOOGLE_HOMEGRAPH_API_BASE_URL,
    GOOGLE_HOMEGRAPH_REQUEST_SYNC_DEBOUNCE_MS,
    GOOGLE_HOMEGRAPH_REPORT_STATE_DEBOUNCE_MS,
    GOOGLE_HOMEGRAPH_REPORT_STATE_ENABLED,
    GOOGLE_DEBUG_ENDPOINTS_ENABLED,
    ALLOWED_CORS_ORIGINS,
    PORTAL_SESSION_COOKIE_NAME,
    PORTAL_SESSION_COOKIE_MAX_AGE_MS,
    PORTAL_SESSION_COOKIE_SECURE,
    PORTAL_SESSION_COOKIE_DOMAIN,
    DEVICE_HEARTBEAT_TIMEOUT_SECONDS,
    DEVICE_HEARTBEAT_INTERVAL_SECONDS,
    ADMIN_CONNECT_TOKEN_TTL_MINUTES,
    DEVICE_TUNNEL_PORT_MIN,
    DEVICE_TUNNEL_PORT_MAX,
    DEVICE_TOKEN_PREFIX,
    ADMIN_CONNECT_TOKEN_PREFIX
};
