{
    'build_from':
        {
            'aarch64': 'ghcr.io/apexinfosysindia/addon-base:15.0.4',
            'amd64': 'ghcr.io/apexinfosysindia/addon-base:15.0.4',
            'armhf': 'ghcr.io/apexinfosysindia/addon-base:15.0.4',
            'armv7': 'ghcr.io/apexinfosysindia/addon-base:15.0.4',
            'i386': 'ghcr.io/apexinfosysindia/addon-base:15.0.4'
        }
}
